version: 2.1
# Define the jobs we want to run for this project
jobs:
    create_infrastructure:
        docker:
            - image: amazon/aws-cli
        steps:
            - checkout
            - run:
                name: Create Cloudformation Stack
                command: |
                    aws cloudformation deploy \
                    --template-file template.yml \
                    --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
                    --region us-east-1
    # Exercise: Config and Deployment
    configure_infrastructure: 
        docker:
            - image: python:3.7-alpine3.11
        steps:
            - checkout
            - add_ssh_keys:
                # You can get this ID in the section where you registered the SSH Key
                fingerprints:
                    - 58:40:4f:52:d1:97:3f:b8:c8:16:bf:a7:60:14:b1:47
            #- run:
             #   name: disable ssh authentication
              #  command: |
               #     mkdir -p ~/.ssh ;
                #    touch ~/.ssh/config ;
                 #   echo 'PubkeyAuthentication yes' > ~/.ssh/config
            - run:
                name: Install Ansible
                command: |
                    apk add --update ansible
            - run:
                name: Run Playbook and Configure server
                command: |
                    ansible-playbook main-remote.yml

workflows:
    createIacCICD:
        jobs:
            - configure_infrastructure


